### ISSUE TITLE
Disabling "watch" feature?

### ISSUE THREAD

**Issue by olalonde** [petruisfan/node-supervisor#161]
I would just like to use supervisor to restart my process when it crashes, is that possible? Would the `-i '.'` flag do it?

`./node_modules/.bin/supervisor -i '.' -q --exec npm start`

**Comment by DelvarWorld** [comment]
I would also like to disable watch to lower the memory footprint of supervisor

**Comment by julien-c** [comment]
You could have a look at `forever` then.

**Comment by petruisfan** [comment]
Hi!

Yes, `-i .` would ignore file changes.
I added better suport in v0.8.

Thx and sorry for the late answer.
