### ISSUE TITLE
Upstart hangs when trying to stop Supervisor

### ISSUE THREAD

**Issue by sg-cc** [petruisfan/node-supervisor#165]
I have an Upstart script which runs my app wrapped in Supervisor. I'm enjoying its ability to both restart a crashed server and restart on file change. My upstart script right now is fashioned thusly:

    script
        exec supervisor \
           --save-pid $PIDFILE \
           --watch $WATCH_PATH \
           --ignore $IGNORE \
           $APPLICATION_PATH \
          >> $LOG
    end script

Running `start mynodeservice` results in expected behaviour. However, running `stop mynodeservice` causes the system to hang (i.e. it can still be terminated by Ctrl+C, but then upstart gets its brains mixed up, thinking the process is still running, until I reboot the whole system).

Is there a reason this is happening? With forever, stopping the service can be done in this way:

    pre-stop script
        exec forever stop $APPLICATION_PATH
    end script

However, supervisor does not have a `stop` command. How can I get it to stop hanging?

**Comment by petruisfan** [comment]
Does adding a stop command help?

**Comment by sg-cc** [comment]
Sorry, I'm still new to Upstart and Linux in general. How would I create a stop command for Supervisor? I tried (excuse the noobishness) killall supervisor, stop supervisor, pkill supervisor, kill {PID}... it still hangs.

**Comment by sg-cc** [comment]
Agh, accidentally closed. See above about noobishness.

**Comment by petruisfan** [comment]
"kill $(cat ${PIDFILE})" should do the trick

**Comment by sg-cc** [comment]
It worked! Thank you!!!!! Closing issue!
