### ISSUE TITLE
Option to turn off "rs to restart" CLI

### ISSUE THREAD

**Issue by ajeffrey** [petruisfan/node-supervisor#166]
Hi there,

I'm running a server using supervisor and I'm simultaneously running a REPL for developer debugging. I updated to the latest supervisor and now it' conflicting with supervisor's REPL - I think it's a good feature but it'd be nice to get an option to turn it off if possible. When I get some time I'll put together a pull request to add an option to turn this off - how does --disable-cli sound?

**Comment by petruisfan** [comment]
Hi Alex,
If you have time, any help is appreciated :)
I would suggest -t | --non-interactive

Thx!

**Comment by ajeffrey** [comment]
ok I've sent over a pull request that adds this feature :)
