### ISSUE TITLE
Application runs using "node app.js" but not using "supervisor app.js"

### ISSUE THREAD

**Issue by Cyberuben** [petruisfan/node-supervisor#168]
I'm trying to get my application to work again. It seems that any time I try to access a page in my expressjs application, the server crashes. There is no errors shown anywhere in the console, but it clearly states "crashing child" after I access a page once. 

If I run the same application using "node app.js", it runs fine and doesn't crash at all. I have supervisor v0.9.1 installed.

**Comment by petruisfan** [comment]
Could you give me a few more details on reproducing the problem? What OS are you using? What version of node? What is the output when it crashes?

**Comment by Cyberuben** [comment]
My bad, apparently the application was reloaded due to a .css file being modified. It hadn't done this before thus I found it weird it happened.
