### ISSUE TITLE
use strict

### ISSUE THREAD

**Issue by mazko** [petruisfan/node-supervisor#184]
~$ npm list -g supervisor
    └── supervisor@0.9.1

    ~$ node --use_strict `which supervisor` 
    /node_modules/supervisor/lib/supervisor.js:341
    var timer = null, mtime = null; crash_queued = false;

    ReferenceError: crash_queued is not defined

Looks like you forgot to declare ```var crash_queued``` :-)

**Comment by petruisfan** [comment]
Fixed. Thx :)
