### ISSUE TITLE
Kill? Killall?

### ISSUE THREAD

**Issue by jaredreich** [petruisfan/node-supervisor#189]
Why can't I stop supervisor from running?
Unless I'm missing something, I can't see within the list of options any 'kill' or 'killall' option.

Thanks in advance

**Comment by petruisfan** [comment]
Doesn't Ctrl+C / Cmd+C do the job?

**Comment by jaredreich** [comment]
My bad, I had some weird conflicts between supervisor, nodemon, and forever that was causing very weird behavior. I'll close sorry to bother you.
