### ISSUE TITLE
CPU high usage for supervisor

### ISSUE THREAD

**Issue by swizardlv** [petruisfan/node-supervisor#192]
When I run 'supervisor ./bin/www' , The node CPU usage become over 100% after supervisor run.
![after](https://cloud.githubusercontent.com/assets/10117682/17239012/4736f8f4-5593-11e6-9a5c-e7b9e9b6d61f.jpg)

When I run `node ./bin/www` the cpu usage is low.
![before](https://cloud.githubusercontent.com/assets/10117682/17238991/22c39518-5593-11e6-9541-5f7c772369aa.jpg)

```
> node -v
v5.2.0
```

**Comment by petruisfan** [comment]
Try with this option:

` --poll-interval 5007`

**Comment by swizardlv** [comment]
@petruisfan I add the option but still high cpu usage.

**Comment by petruisfan** [comment]
Is node_modules or bower_components inside the folder you are watching?

**Comment by swizardlv** [comment]
@petruisfan  , I think so, How can i ignore them?

**Comment by petruisfan** [comment]
-i node_modules,bower_components
