### ISSUE TITLE
how to debug view engine EJS *.ejs file 

### ISSUE THREAD

**Issue by pei-han** [petruisfan/node-supervisor#193]
look at the title

**Comment by petruisfan** [comment]
Not sure I understand... could you give some more details?

**Comment by pei-han** [comment]
![image](https://cloud.githubusercontent.com/assets/1300292/17998013/ba31806e-6ba4-11e6-95d1-affea59d98dc.png)
![image](https://cloud.githubusercontent.com/assets/1300292/17998032/cf5f9f52-6ba4-11e6-9b7b-ae02db27f134.png)
@petruisfan 
Look two images above,that red block on the second image is not found on the first image.
So i can not debug EJS files with *.ejs suffix.
Can you help me?thank a lot.

**Comment by petruisfan** [comment]
Sorry my friend, but this has nothing to do with node-supervisor

**Comment by pei-han** [comment]
@petruisfan 
Thx.
 Whether or not add this feature on road map of node-inspector ?

**Comment by petruisfan** [comment]
This is **node-supervisor**, not node-inspector

**Comment by pei-han** [comment]
@petruisfan 
So sorry.
