### ISSUE TITLE
support for --inspect

### ISSUE THREAD

**Issue by caleb0199** [petruisfan/node-supervisor#200]
Now that we can use chrome dev tools to debug node applications (great post regarding this from Paul Irish here: https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.sx88bf87q ), I'd love to be able to use supervisor with this argument (passed through to node).

**Comment by petruisfan** [comment]
Nice feature :) thx for the info! Didn't know about it...

**Comment by caleb0199** [comment]
Thanks for the quick response!
